Repository Stooa/Stooa, pull requests merged in 2021-12, with the labels that each got.

#114 Add Jitsi Nginx
  jitsi/.docker/nginx-dev/default.conf.template
  jitsi/.docker/nginx-prod/default.conf.template
  jitsi/Dockerfile
Labels: feature

#108 Update packages
  frontend/package.json
  frontend/yarn.lock
Labels: dependencies

#120 Update symfony/serializer to 5.3.12
  backend/composer.lock
Labels: dependencies

#128 Remove fishbowl overlap constraint
  backend/src/Entity/Fishbowl.php
  backend/src/Validator/Constraints/OverlapFishbowl.php
  backend/src/Validator/Constraints/OverlapFishbowlValidator.php
Labels: feature

#131 Fix guest users without (Me) copy during pre fishbowl
  frontend/components/App/Participants/Participant.tsx
Labels: bug
