Repository Stooa/Stooa, pull requests merged in 2021-11, with the labels that each got.

#67 Add fishbowl test slug for fixtures
  backend/src/DataFixtures/DefaultFixtures.php
Labels: bug

#69 Fix internal error on guest access to fishbowl
  backend/src/Resolver/FishbowlCreatorResolver.php
Labels: bug

#68 Use fixtures on local environment too
  Makefile
Labels: improvement

#73 Add link to home
  README.md
Labels: docs

#71 Fallback to default language
  .editorconfig
  frontend/components/Common/CopyUrl/index.tsx
  frontend/components/Common/LanguageSwitcher/index.tsx
  frontend/components/Web/Forms/create-fishbowl.tsx
  frontend/components/Web/Forms/register.tsx
  frontend/i18n.js
  frontend/i18n.json
  frontend/next-env.d.ts
  frontend/pages/_document.tsx
Labels: bug

#76 Add async to messenger consume
  backend/.docker/app-prod/php-fpm.sh
Labels: improvement

#81 Bug: Social icons alignment when name is too long in participants list
  frontend/components/App/Participants/styles.ts
Labels: bug

#84 Fix token creation when two fishbowls are close in time by the same host
  backend/composer.json
  backend/composer.lock
  backend/src/EventSubscriber/JWTCreatedSubscriber.php
  backend/src/Factory/UserFactory.php
  backend/src/Service/FishbowlService.php
  backend/symfony.lock
  backend/tests/Functional/RefreshTokenTest.php
  backend/tests/Integration/FishbowlRepositoryTest.php
  backend/tests/Integration/ParticipantRepositoryTest.php
  backend/tests/Unit/FishbowlServiceTest.php
  backend/tests/Unit/JWTCreatedSubscriberTest.php
  frontend/lib/auth/index.ts
  frontend/lib/jitsi-modules/Conference.js
Labels: bug

#89 Add GET operation to fishbowl, guest and user entities. Needed by api platform generator
  backend/src/Entity/Fishbowl.php
  backend/src/Entity/Guest.php
  backend/src/Entity/User.php
  frontend/types/api-platform/interfaces/fishbowl.ts
  frontend/types/api-platform/interfaces/guest.ts
  frontend/types/api-platform/interfaces/participant.ts
  frontend/types/api-platform/interfaces/user.ts
Labels: improvement

#90 Add backend error and constraints translations via new header
  backend/config/services.yaml
  backend/psalm-baseline.xml
  backend/psalm.xml
  backend/src/Entity/Participant.php
  backend/src/Entity/User.php
  backend/src/EventSubscriber/LocaleSubscriber.php
  backend/src/EventSubscriber/TranslateJWTAuthenticationFailureResponse.php
  backend/src/Model/ChangePasswordLoggedInput.php
  backend/src/Validator/Constraints/FutureFishbowl.php
  backend/src/Validator/Constraints/OverlapFishbowl.php
  backend/src/Validator/Constraints/SameUserPassword.php
  backend/src/Validator/Constraints/ValidResetPasswordToken.php
  backend/tests/Functional/LoginFunctionalTest.php
  backend/tests/Functional/RefreshTokenFunctionalTest.php
  backend/tests/Unit/LocaleSubscriberTest.php
  backend/translations/messages.ca.yaml
  backend/translations/messages.en.yaml
  backend/translations/messages.es.yaml
  backend/translations/validators/validators.ca.yaml
  backend/translations/validators/validators.en.yaml
  backend/translations/validators/validators.es.yaml
  frontend/components/Web/Forms/FormError.tsx
  frontend/components/Web/Forms/FormErrorParser.ts
  frontend/contexts/AuthContext.tsx
  frontend/contexts/StooaManager.tsx
  frontend/hocs/withIsFishbowlEnded.js
  frontend/hooks/usePersistLocaleCookie.ts
  frontend/lib/LocaleCookie.ts
  frontend/lib/api.js
  frontend/lib/apollo-client.js
  frontend/lib/auth/index.ts
Labels: improvement
