Repository Stooa/Stooa, pull requests merged in 2022-01, with the labels that each got.

#133 Keep track muted when changing device
  frontend/lib/jitsi-modules/Tracks.js
Labels: bug

#130 Make Fishbowl title optional
  backend/src/Admin/FishbowlAdmin.php
  backend/src/Entity/Fishbowl.php
  backend/src/EventSubscriber/FishbowlSubscriber.php
  backend/src/Service/FishbowlService.php
  backend/src/Stage/FishbowlValidateStage.php
  backend/tests/Unit/FishbowlServiceTest.php
  backend/translations/messages.ca.yaml
  backend/translations/messages.de.yaml
  backend/translations/messages.en.yaml
  backend/translations/messages.es.yaml
  backend/translations/messages.fr.yaml
  frontend/components/Common/Fields/Input.tsx
  frontend/components/Web/Forms/CreateFishbowl.tsx
  frontend/locales/ca/form.json
  frontend/locales/de/form.json
  frontend/locales/en/form.json
  frontend/locales/es/form.json
  frontend/locales/fr/form.json
  frontend/pages/fishbowl/create.tsx
Labels: feature

#136 Add default values in Fishbowl creation
  frontend/components/Common/Fields/DatePicker.tsx
  frontend/components/Web/Forms/CreateFishbowl.tsx
  frontend/lib/helpers.js
Labels: feature

#162 Add Codecov
  .github/workflows/backend-test.yaml
  .github/workflows/frontend-test.yaml
  frontend/.gitignore
  frontend/jest.config.js
Labels: improvement

#165 Fix warning on import color.json
  frontend/ui/settings.js
Labels: bug

#166 Fix error when closing a fishbowl
  frontend/components/App/Participants/index.tsx
Labels: bug

#168 auth variable might be null
  frontend/lib/jitsi-modules/Conference.js
Labels: bug

#170 Correctly dispose tracks when finishing a fishbowl
  frontend/contexts/StooaManager.tsx
  frontend/lib/jitsi-modules/Conference.js
  frontend/lib/jitsi-modules/Tracks.js
  frontend/lib/jitsi.js
Labels: bug

#138 Change redirect when clicking CTA to Register instead of login
  frontend/contexts/AuthContext.tsx
Labels: improvement

#172 Add e2e test with Cypress
  .github/workflows/frontend-lint.yaml
  .github/workflows/frontend-test.yaml
  frontend/.babelrc
  frontend/.gitignore
  frontend/.nycrc
  frontend/.prettierignore
  frontend/cypress.json
  frontend/jest.config.js
  frontend/package.json
  frontend/pages/api/__coverage__.ts
  frontend/tests/e2e/features/common/index.ts
  frontend/tests/e2e/features/home.feature
  frontend/tests/e2e/features/home/home.ts
  frontend/tests/e2e/plugins/index.js
  frontend/tests/e2e/support/index.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: improvement

#174 Use NPM instead of Yarn
  .github/workflows/backend-lint.yaml
  .github/workflows/backend-qa.yaml
  .github/workflows/backend-test.yaml
  .github/workflows/frontend-build.yaml
  .github/workflows/frontend-lint.yaml
  .github/workflows/frontend-test.yaml
  frontend/.gitignore
  frontend/.nvmrc
  frontend/Dockerfile
  frontend/contexts/AuthContext.tsx
  frontend/contexts/DevicesContext.tsx
  frontend/contexts/StooaManager.tsx
  frontend/jest.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/index.tsx
  frontend/yarn.lock
Labels: improvement

#175 Fix local docker compose
  docker-compose.yaml
Labels: bug

#176 Avoid failing E2E frontend tests on PRs opened from a fork repository
  .github/workflows/frontend-test.yaml
Labels: bug

#177 Move jest tests inside tests folder
  frontend/.nycrc
  frontend/jest.config.js
  frontend/tests/unit/components/buttonJoin.test.js
  frontend/tests/unit/pages/landing.test.js
  frontend/tests/unit/setup/canvas.js
  frontend/tests/unit/setup/fileTransformer.js
  frontend/tests/unit/setup/jest.setup.js
Labels: improvement

#179 Remove HSTS on localhost
  backend/.docker/nginx-dev/default.conf.template
  frontend/.docker/nginx-dev/default.conf.template
Labels: bug

#183 Add dependencies label to renovate bot
  .github/renovate.json
Labels: improvement

#190 Add typescript compiler build
  .github/workflows/frontend-qa.yaml
Labels: improvement

#192 Dipose track if video is not found
  frontend/src/components/App/FishbowlPreJoin/index.tsx
Labels: bug

#207 Add more tests for the home
  frontend/tests/e2e/features/common/index.ts
  frontend/tests/e2e/features/home.feature
  frontend/tests/e2e/features/home/home.ts
  frontend/tests/e2e/support/index.ts
  frontend/tests/e2e/support/tokens.ts
Labels: improvement

#249 Finished home tests
  frontend/tests/e2e/features/common/index.ts
  frontend/tests/e2e/features/home.feature
  frontend/tests/e2e/features/home/home.ts
  frontend/tests/e2e/fixtures/self-user.json
Labels: improvement

#261 Allow to execute Next.js outside Docker
  .env
  backend/.env
  docker-compose.yaml
  frontend/tsconfig.json
  jitsi/.docker/nginx-dev/default.conf.template
Labels: improvement
