Repository Stooa/Stooa, pull requests merged in 2022-06, with the labels that each got.

#476 [Feature] Reactions
  frontend/locales/ca/fishbowl.json
  frontend/locales/en/fishbowl.json
  frontend/locales/es/fishbowl.json
  frontend/locales/fr/fishbowl.json
  frontend/locales/id/fishbowl.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/App/ButtonConfig/index.tsx
  frontend/src/components/App/ButtonConfig/styles.ts
  frontend/src/components/App/ButtonContextMenu/index.tsx
  frontend/src/components/App/ButtonJoin/index.tsx
  frontend/src/components/App/ButtonJoin/styles.ts
  frontend/src/components/App/ButtonMic/index.tsx
  frontend/src/components/App/ButtonMic/styles.ts
  frontend/src/components/App/ButtonVideo/index.tsx
  frontend/src/components/App/ButtonVideo/styles.ts
  frontend/src/components/App/Fishbowl/index.tsx
  frontend/src/components/App/Reactions/ReactionEmoji/index.tsx
  frontend/src/components/App/Reactions/ReactionEmoji/styles.ts
  frontend/src/components/App/Reactions/ReactionsButton/index.tsx
  frontend/src/components/App/Reactions/ReactionsButton/styles.ts
  frontend/src/components/App/Reactions/ReactionsEmojis.tsx
  frontend/src/components/App/Reactions/ReactionsReceiver/index.tsx
  frontend/src/components/App/Reactions/ReactionsReceiver/styles.ts
  frontend/src/components/App/Reactions/ReactionsSender/index.tsx
  frontend/src/components/App/Reactions/ReactionsSender/styles.ts
  frontend/src/components/App/ToolBar/index.tsx
  frontend/src/components/App/ToolBar/styles.ts
  frontend/src/hooks/useDebouce.ts
  frontend/src/layouts/App/styles.ts
  frontend/src/layouts/Home/styles.ts
  frontend/src/lib/Reactions/Reactions.ts
  frontend/src/lib/analytics.ts
  frontend/src/lib/jitsi-modules/Conference.js
  frontend/src/lib/jitsi-modules/Events.js
  frontend/src/pages/fb/[fid].tsx
  frontend/src/types/analytics.ts
  frontend/src/types/reactions.ts
  frontend/src/ui/animations/motion/reactions.ts
  frontend/src/ui/settings.js
  frontend/src/ui/svg/emojis/agree.svg
  frontend/src/ui/svg/emojis/applause.svg
  frontend/src/ui/svg/emojis/curious.svg
  frontend/src/ui/svg/emojis/disagree.svg
  frontend/src/ui/svg/emojis/insightful.svg
  frontend/src/ui/svg/emojis/joy.svg
  frontend/src/ui/svg/emojis/laugh.svg
  frontend/src/ui/svg/emojis/love.svg
  frontend/src/ui/svg/emojis/plus.svg
  frontend/src/ui/svg/emojis/reactions-button.svg
  frontend/src/ui/svg/emojis/wave.svg
  frontend/tests/e2e/features/common/index.ts
  frontend/tests/e2e/features/fishbowl/fishbowl.ts
  frontend/tests/e2e/features/reactions.feature
  frontend/tests/e2e/features/reactions/reactions.ts
  frontend/tests/unit/components/App/ButtonContextMenu/ButtonContextMenu.test.js
  frontend/tests/unit/components/App/Reactions/ReactionEmoji.test.js
  frontend/tests/unit/components/App/Reactions/ReactionsButton.test.js
  frontend/tests/unit/components/App/Reactions/ReactionsReceiver.test.js
  frontend/tests/unit/components/App/Reactions/ReactionsSender.test.js
Labels: feature

#487 Release 1.0.0
  frontend/CHANGELOG.md
Labels: Release

#488 Move changelog to root folder
  CHANGELOG.md
Labels: bug

#489 Add new package.json in root folder to generate CHANGELOG
  .gitignore
  frontend/package-lock.json
  frontend/package.json
  package-lock.json
  package.json
Labels: improvement

#498 Reset token cookie before setting it
  frontend/src/lib/auth/index.ts
Labels: bug
